services:
  postgres:
    image: postgres:17
    container_name: security-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: attt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - security-network

  kali-worker:
    build:
      context: ./docker/kali-worker
    container_name: kali-worker
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - security-network
    volumes:
      # Ánh xạ thư mục chứa script vào trong Kali
      - ./backend/src/main/resources/scripts:/scripts
    
networks:
  security-network:


volumes:
  postgres_data:
