<<<<<<< HEAD
<<<<<<< HEAD
spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/attt
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=true

=======
server.port=8080
spring.application.name=demo-backend
>>>>>>> origin/main
=======
server.port=8080
spring.application.name=demo-backend
>>>>>>> origin/main
